spring:
  application:
    name: diceware
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  error:
    include-message: always
  port: 18981
  servlet:
    context-path: /diceware

diceware:
  # noinspection SpringBootApplicationYaml
  word-list: word-list.txt